PR#7506: Range Locking: Implementation: fix issues detected by CI part 5
Avoid this error

./utilities/transactions/lock/range/range_tree/ft/comparator.h:47:32:
error: reference to 'DB' is ambiguous

By removing the toku::DB as it is unused anyway.